language: node_js
node_js:
  - "0.10"
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
branches:
  only:
    - master
before_script:
  - bundle install
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
